spring.application.name=OrganizaAI
spring.datasource.url=jdbc:postgresql://localhost:5432/organiza_ai
spring.datasource.username=postgres
spring.datasource.password=842473

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect